config/routes.rb
Rails.application.routes.draw do
  resources :connections, only: [:new, :index]
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  def is_host_available?
    HostAvailability.port_open?(self.host, self.port)
  end
end

app/models/dbms.rb
class DBMS < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def index
    @connections = Connection.order(:name)
  end

  def new
    @connection = Connection.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connection_helper.rb
module ConnectionHelper
  require 'connPort.rb'

  def port_open?(host, port)
    ConnPort.new.port_open?(host, port)
  end
end

app/views/connection/_item.html.erb
<div class="column">
  <div class="ui special cards">
    <div class="card">
      <a class="ui right corner label">
        <i id='connBtn' class="big circle gray icon"></i>
      </a>
      <div class="blurring dimmable image">
        <div class="ui dimmer">
          <div class="content">
            <div class="center">
              <div class="ui inverted button" style="position: absolute; bottom: 5px; right: 0;">Open Connection</div>
            </div>
          </div>
        </div>
        <img src="https://s3.amazonaws.com/hackerleague-production/organizations/logos/512bb56489c01624c8000016/thumb.png">
      </div>
      <div class="content">
        <a class="header item" data-content="<%= item.name %>">
          <%= truncate(item.name, length: 22) %>
        </a>
        <div class="meta">
          <div>
            <i class="user icon"></i><%= item.user %>
          </div>
          <div>
            <i class="sitemap icon"></i><%= "#{item.host}:#{item.port}"  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.special.cards .image').dimmer({
    on: 'hover'
  });

  $('.item').popup();

  var connStts = <%= port_open?('localhost', 27017) %>;

  setInterval(function(){
    if (<%= port_open?('localhost', 27017) %> == true){
      $('.special.cards #connBtn').removeClass().addClass('big circle green icon')
    } else if (<%= port_open?('localhost', 27017) %> == false){
      $('.special.cards #connBtn').removeClass().addClass('big circle red icon')
    }
    $(".special.cards #connBtn").load(location.href+" .special.cards #connBtn>*", '');
  }, 3000);

</script>

app/views/connections/_connection.html.erb
<div class="column">
  <div class="ui special cards">
    <div class="card">
      <a class="ui right corner label">
        <i class="big circle <%= if connection.is_host_available? then 'green' else 'red' end %> icon"></i>
      </a>
      <div class="blurring dimmable image">
        <div class="ui dimmer">
          <div class="content">
            <div class="center">
              <div class="ui inverted button">Open Connection</div>
            </div>
          </div>
        </div>
        <img src="http://semantic-ui.com/images/avatar2/large/kristy.png">
      </div>
      <div class="content">
        <a class="header item" data-content="<%= connection.name %>">
          <%= truncate(connection.name, length: 22) %>
        </a>
        <div class="meta">
          <div>
            <i class="user icon"></i><%= connection.user %>
          </div>
          <div>
            <i class="sitemap icon"></i><%= "#{connection.host}:#{connection.port}"  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/connections/_form.html.erb
<%= render layout: 'shared/modal' do %>
  <%= simple_form_for connection, html: {class: 'ui form'} do |f| %>
    <div class="field">
      <%= f.input :name %>
    </div>

    <div class="field">
      <%= f.input :host %>
    </div>

    <div class="field">
      <%= f.input :user %>
    </div>

    <div class="field">
      <%= f.input :password %>
    </div>

    <div class="field">
      <%= f.input :port %>
    </div>
  <% end %>
<% end %>

app/views/connections/index.html.erb
<div class="ui clearing">
  <h1 class="ui left floated header">My Connections</h1>

  <%= link_to new_connection_path, remote: true, class: 'large ui right floated labeled blue icon button' do %>
    <i class="plus icon"></i>
    Add Connection
  <% end %>
</div>

<div class="ui section clearing divider"></div>

<div class="ui stackable four column grid">
  <%= render partial: 'connection', collection: @connections %>
</div>

<div id="modal-form"></div>

app/views/connections/new.js.erb
$("#modal-form").html("<%= j render partial: 'form', locals: {connection: @connection} %>");
$('#modal').modal('setting', 'transition', 'fade up').modal('show');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DB Admin</title>
    <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- menu -->
    <div class="ui fixed inverted menu">
      <div class="ui container">
        <a href="#" class="header item">
          <h4>
            <i class="diamond icon"></i>
            DB ADMIN
          </h4>
        </a>

        <a class="item">
          About Us
        </a>
      </div>
    </div>

    <div class="ui main container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_modal.html.erb
<div id="modal" class="ui small modal">
  <div class="header">
    Connection
  </div>
  <div class="content">
    <%= yield %>
  </div>
  <div class="actions">
    <div class="ui negative button">
      No
    </div>
    <div class="ui positive right labeled icon button">
      Yes
      <i class="checkmark icon"></i>
    </div>
  </div>
</div>